// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/zkart/dbFiles/proto/admin.proto
// Protobuf Java Version: 4.29.3

package com.zkart.model;

public final class AdminProto {
  private AdminProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AdminProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code AdminUserType}
   */
  public enum AdminUserType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUPER_USER = 0;</code>
     */
    SUPER_USER(0),
    /**
     * <code>ROOT_USER = 1;</code>
     */
    ROOT_USER(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        AdminUserType.class.getName());
    }
    /**
     * <code>SUPER_USER = 0;</code>
     */
    public static final int SUPER_USER_VALUE = 0;
    /**
     * <code>ROOT_USER = 1;</code>
     */
    public static final int ROOT_USER_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AdminUserType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AdminUserType forNumber(int value) {
      switch (value) {
        case 0: return SUPER_USER;
        case 1: return ROOT_USER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AdminUserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AdminUserType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AdminUserType>() {
            public AdminUserType findValueByNumber(int number) {
              return AdminUserType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zkart.model.AdminProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final AdminUserType[] VALUES = values();

    public static AdminUserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AdminUserType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AdminUserType)
  }

  public interface AdminOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Admin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.BaseUser adminUser = 1;</code>
     * @return Whether the adminUser field is set.
     */
    boolean hasAdminUser();
    /**
     * <code>.BaseUser adminUser = 1;</code>
     * @return The adminUser.
     */
    com.zkart.model.BaseUserProto.BaseUser getAdminUser();
    /**
     * <code>.BaseUser adminUser = 1;</code>
     */
    com.zkart.model.BaseUserProto.BaseUserOrBuilder getAdminUserOrBuilder();

    /**
     * <code>.AdminUserType userType = 2;</code>
     * @return The enum numeric value on the wire for userType.
     */
    int getUserTypeValue();
    /**
     * <code>.AdminUserType userType = 2;</code>
     * @return The userType.
     */
    com.zkart.model.AdminProto.AdminUserType getUserType();
  }
  /**
   * Protobuf type {@code Admin}
   */
  public static final class Admin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Admin)
      AdminOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Admin.class.getName());
    }
    // Use Admin.newBuilder() to construct.
    private Admin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Admin() {
      userType_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.AdminProto.internal_static_Admin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.AdminProto.internal_static_Admin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.AdminProto.Admin.class, com.zkart.model.AdminProto.Admin.Builder.class);
    }

    private int bitField0_;
    public static final int ADMINUSER_FIELD_NUMBER = 1;
    private com.zkart.model.BaseUserProto.BaseUser adminUser_;
    /**
     * <code>.BaseUser adminUser = 1;</code>
     * @return Whether the adminUser field is set.
     */
    @java.lang.Override
    public boolean hasAdminUser() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.BaseUser adminUser = 1;</code>
     * @return The adminUser.
     */
    @java.lang.Override
    public com.zkart.model.BaseUserProto.BaseUser getAdminUser() {
      return adminUser_ == null ? com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance() : adminUser_;
    }
    /**
     * <code>.BaseUser adminUser = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.BaseUserProto.BaseUserOrBuilder getAdminUserOrBuilder() {
      return adminUser_ == null ? com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance() : adminUser_;
    }

    public static final int USERTYPE_FIELD_NUMBER = 2;
    private int userType_ = 0;
    /**
     * <code>.AdminUserType userType = 2;</code>
     * @return The enum numeric value on the wire for userType.
     */
    @java.lang.Override public int getUserTypeValue() {
      return userType_;
    }
    /**
     * <code>.AdminUserType userType = 2;</code>
     * @return The userType.
     */
    @java.lang.Override public com.zkart.model.AdminProto.AdminUserType getUserType() {
      com.zkart.model.AdminProto.AdminUserType result = com.zkart.model.AdminProto.AdminUserType.forNumber(userType_);
      return result == null ? com.zkart.model.AdminProto.AdminUserType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getAdminUser());
      }
      if (userType_ != com.zkart.model.AdminProto.AdminUserType.SUPER_USER.getNumber()) {
        output.writeEnum(2, userType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAdminUser());
      }
      if (userType_ != com.zkart.model.AdminProto.AdminUserType.SUPER_USER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, userType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.AdminProto.Admin)) {
        return super.equals(obj);
      }
      com.zkart.model.AdminProto.Admin other = (com.zkart.model.AdminProto.Admin) obj;

      if (hasAdminUser() != other.hasAdminUser()) return false;
      if (hasAdminUser()) {
        if (!getAdminUser()
            .equals(other.getAdminUser())) return false;
      }
      if (userType_ != other.userType_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAdminUser()) {
        hash = (37 * hash) + ADMINUSER_FIELD_NUMBER;
        hash = (53 * hash) + getAdminUser().hashCode();
      }
      hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + userType_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.AdminProto.Admin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.AdminProto.Admin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.AdminProto.Admin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.AdminProto.Admin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.AdminProto.Admin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.AdminProto.Admin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.AdminProto.Admin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.AdminProto.Admin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.AdminProto.Admin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.AdminProto.Admin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.AdminProto.Admin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.AdminProto.Admin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.AdminProto.Admin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Admin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Admin)
        com.zkart.model.AdminProto.AdminOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.AdminProto.internal_static_Admin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.AdminProto.internal_static_Admin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.AdminProto.Admin.class, com.zkart.model.AdminProto.Admin.Builder.class);
      }

      // Construct using com.zkart.model.AdminProto.Admin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getAdminUserFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        adminUser_ = null;
        if (adminUserBuilder_ != null) {
          adminUserBuilder_.dispose();
          adminUserBuilder_ = null;
        }
        userType_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.AdminProto.internal_static_Admin_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.AdminProto.Admin getDefaultInstanceForType() {
        return com.zkart.model.AdminProto.Admin.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.AdminProto.Admin build() {
        com.zkart.model.AdminProto.Admin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.AdminProto.Admin buildPartial() {
        com.zkart.model.AdminProto.Admin result = new com.zkart.model.AdminProto.Admin(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.zkart.model.AdminProto.Admin result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.adminUser_ = adminUserBuilder_ == null
              ? adminUser_
              : adminUserBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userType_ = userType_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.AdminProto.Admin) {
          return mergeFrom((com.zkart.model.AdminProto.Admin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.AdminProto.Admin other) {
        if (other == com.zkart.model.AdminProto.Admin.getDefaultInstance()) return this;
        if (other.hasAdminUser()) {
          mergeAdminUser(other.getAdminUser());
        }
        if (other.userType_ != 0) {
          setUserTypeValue(other.getUserTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAdminUserFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                userType_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.zkart.model.BaseUserProto.BaseUser adminUser_;
      private com.google.protobuf.SingleFieldBuilder<
          com.zkart.model.BaseUserProto.BaseUser, com.zkart.model.BaseUserProto.BaseUser.Builder, com.zkart.model.BaseUserProto.BaseUserOrBuilder> adminUserBuilder_;
      /**
       * <code>.BaseUser adminUser = 1;</code>
       * @return Whether the adminUser field is set.
       */
      public boolean hasAdminUser() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.BaseUser adminUser = 1;</code>
       * @return The adminUser.
       */
      public com.zkart.model.BaseUserProto.BaseUser getAdminUser() {
        if (adminUserBuilder_ == null) {
          return adminUser_ == null ? com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance() : adminUser_;
        } else {
          return adminUserBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseUser adminUser = 1;</code>
       */
      public Builder setAdminUser(com.zkart.model.BaseUserProto.BaseUser value) {
        if (adminUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          adminUser_ = value;
        } else {
          adminUserBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.BaseUser adminUser = 1;</code>
       */
      public Builder setAdminUser(
          com.zkart.model.BaseUserProto.BaseUser.Builder builderForValue) {
        if (adminUserBuilder_ == null) {
          adminUser_ = builderForValue.build();
        } else {
          adminUserBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.BaseUser adminUser = 1;</code>
       */
      public Builder mergeAdminUser(com.zkart.model.BaseUserProto.BaseUser value) {
        if (adminUserBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            adminUser_ != null &&
            adminUser_ != com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance()) {
            getAdminUserBuilder().mergeFrom(value);
          } else {
            adminUser_ = value;
          }
        } else {
          adminUserBuilder_.mergeFrom(value);
        }
        if (adminUser_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.BaseUser adminUser = 1;</code>
       */
      public Builder clearAdminUser() {
        bitField0_ = (bitField0_ & ~0x00000001);
        adminUser_ = null;
        if (adminUserBuilder_ != null) {
          adminUserBuilder_.dispose();
          adminUserBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.BaseUser adminUser = 1;</code>
       */
      public com.zkart.model.BaseUserProto.BaseUser.Builder getAdminUserBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAdminUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseUser adminUser = 1;</code>
       */
      public com.zkart.model.BaseUserProto.BaseUserOrBuilder getAdminUserOrBuilder() {
        if (adminUserBuilder_ != null) {
          return adminUserBuilder_.getMessageOrBuilder();
        } else {
          return adminUser_ == null ?
              com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance() : adminUser_;
        }
      }
      /**
       * <code>.BaseUser adminUser = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.zkart.model.BaseUserProto.BaseUser, com.zkart.model.BaseUserProto.BaseUser.Builder, com.zkart.model.BaseUserProto.BaseUserOrBuilder> 
          getAdminUserFieldBuilder() {
        if (adminUserBuilder_ == null) {
          adminUserBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.zkart.model.BaseUserProto.BaseUser, com.zkart.model.BaseUserProto.BaseUser.Builder, com.zkart.model.BaseUserProto.BaseUserOrBuilder>(
                  getAdminUser(),
                  getParentForChildren(),
                  isClean());
          adminUser_ = null;
        }
        return adminUserBuilder_;
      }

      private int userType_ = 0;
      /**
       * <code>.AdminUserType userType = 2;</code>
       * @return The enum numeric value on the wire for userType.
       */
      @java.lang.Override public int getUserTypeValue() {
        return userType_;
      }
      /**
       * <code>.AdminUserType userType = 2;</code>
       * @param value The enum numeric value on the wire for userType to set.
       * @return This builder for chaining.
       */
      public Builder setUserTypeValue(int value) {
        userType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.AdminUserType userType = 2;</code>
       * @return The userType.
       */
      @java.lang.Override
      public com.zkart.model.AdminProto.AdminUserType getUserType() {
        com.zkart.model.AdminProto.AdminUserType result = com.zkart.model.AdminProto.AdminUserType.forNumber(userType_);
        return result == null ? com.zkart.model.AdminProto.AdminUserType.UNRECOGNIZED : result;
      }
      /**
       * <code>.AdminUserType userType = 2;</code>
       * @param value The userType to set.
       * @return This builder for chaining.
       */
      public Builder setUserType(com.zkart.model.AdminProto.AdminUserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        userType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.AdminUserType userType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Admin)
    }

    // @@protoc_insertion_point(class_scope:Admin)
    private static final com.zkart.model.AdminProto.Admin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.AdminProto.Admin();
    }

    public static com.zkart.model.AdminProto.Admin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Admin>
        PARSER = new com.google.protobuf.AbstractParser<Admin>() {
      @java.lang.Override
      public Admin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Admin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Admin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.AdminProto.Admin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Admin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Admin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#com/zkart/dbFiles/proto/admin.proto\032&c" +
      "om/zkart/dbFiles/proto/baseUser.proto\"G\n" +
      "\005Admin\022\034\n\tadminUser\030\001 \001(\0132\t.BaseUser\022 \n\010" +
      "userType\030\002 \001(\0162\016.AdminUserType*.\n\rAdminU" +
      "serType\022\016\n\nSUPER_USER\020\000\022\r\n\tROOT_USER\020\001B\035" +
      "\n\017com.zkart.modelB\nAdminProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zkart.model.BaseUserProto.getDescriptor(),
        });
    internal_static_Admin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Admin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Admin_descriptor,
        new java.lang.String[] { "AdminUser", "UserType", });
    descriptor.resolveAllFeaturesImmutable();
    com.zkart.model.BaseUserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
