// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/zkart/dbFiles/proto/coupon.proto
// Protobuf Java Version: 4.29.3

package com.zkart.model;

public final class CouponProto {
  private CouponProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      CouponProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CouponOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Coupon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string dateIssued = 2;</code>
     * @return The dateIssued.
     */
    java.lang.String getDateIssued();
    /**
     * <code>string dateIssued = 2;</code>
     * @return The bytes for dateIssued.
     */
    com.google.protobuf.ByteString
        getDateIssuedBytes();

    /**
     * <code>string validTill = 3;</code>
     * @return The validTill.
     */
    java.lang.String getValidTill();
    /**
     * <code>string validTill = 3;</code>
     * @return The bytes for validTill.
     */
    com.google.protobuf.ByteString
        getValidTillBytes();

    /**
     * <code>int32 userId = 4;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>int32 issuedForOrderId = 5;</code>
     * @return The issuedForOrderId.
     */
    int getIssuedForOrderId();

    /**
     * <code>int32 discountPercent = 6;</code>
     * @return The discountPercent.
     */
    int getDiscountPercent();

    /**
     * <code>bool isUsed = 7;</code>
     * @return The isUsed.
     */
    boolean getIsUsed();

    /**
     * <code>int32 usedOnOrderId = 8;</code>
     * @return The usedOnOrderId.
     */
    int getUsedOnOrderId();
  }
  /**
   * Protobuf type {@code Coupon}
   */
  public static final class Coupon extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Coupon)
      CouponOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Coupon.class.getName());
    }
    // Use Coupon.newBuilder() to construct.
    private Coupon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Coupon() {
      id_ = "";
      dateIssued_ = "";
      validTill_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.CouponProto.internal_static_Coupon_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.CouponProto.internal_static_Coupon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.CouponProto.Coupon.class, com.zkart.model.CouponProto.Coupon.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATEISSUED_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dateIssued_ = "";
    /**
     * <code>string dateIssued = 2;</code>
     * @return The dateIssued.
     */
    @java.lang.Override
    public java.lang.String getDateIssued() {
      java.lang.Object ref = dateIssued_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateIssued_ = s;
        return s;
      }
    }
    /**
     * <code>string dateIssued = 2;</code>
     * @return The bytes for dateIssued.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateIssuedBytes() {
      java.lang.Object ref = dateIssued_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateIssued_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALIDTILL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object validTill_ = "";
    /**
     * <code>string validTill = 3;</code>
     * @return The validTill.
     */
    @java.lang.Override
    public java.lang.String getValidTill() {
      java.lang.Object ref = validTill_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        validTill_ = s;
        return s;
      }
    }
    /**
     * <code>string validTill = 3;</code>
     * @return The bytes for validTill.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValidTillBytes() {
      java.lang.Object ref = validTill_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        validTill_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private int userId_ = 0;
    /**
     * <code>int32 userId = 4;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int ISSUEDFORORDERID_FIELD_NUMBER = 5;
    private int issuedForOrderId_ = 0;
    /**
     * <code>int32 issuedForOrderId = 5;</code>
     * @return The issuedForOrderId.
     */
    @java.lang.Override
    public int getIssuedForOrderId() {
      return issuedForOrderId_;
    }

    public static final int DISCOUNTPERCENT_FIELD_NUMBER = 6;
    private int discountPercent_ = 0;
    /**
     * <code>int32 discountPercent = 6;</code>
     * @return The discountPercent.
     */
    @java.lang.Override
    public int getDiscountPercent() {
      return discountPercent_;
    }

    public static final int ISUSED_FIELD_NUMBER = 7;
    private boolean isUsed_ = false;
    /**
     * <code>bool isUsed = 7;</code>
     * @return The isUsed.
     */
    @java.lang.Override
    public boolean getIsUsed() {
      return isUsed_;
    }

    public static final int USEDONORDERID_FIELD_NUMBER = 8;
    private int usedOnOrderId_ = 0;
    /**
     * <code>int32 usedOnOrderId = 8;</code>
     * @return The usedOnOrderId.
     */
    @java.lang.Override
    public int getUsedOnOrderId() {
      return usedOnOrderId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dateIssued_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, dateIssued_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(validTill_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, validTill_);
      }
      if (userId_ != 0) {
        output.writeInt32(4, userId_);
      }
      if (issuedForOrderId_ != 0) {
        output.writeInt32(5, issuedForOrderId_);
      }
      if (discountPercent_ != 0) {
        output.writeInt32(6, discountPercent_);
      }
      if (isUsed_ != false) {
        output.writeBool(7, isUsed_);
      }
      if (usedOnOrderId_ != 0) {
        output.writeInt32(8, usedOnOrderId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dateIssued_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, dateIssued_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(validTill_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, validTill_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userId_);
      }
      if (issuedForOrderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, issuedForOrderId_);
      }
      if (discountPercent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, discountPercent_);
      }
      if (isUsed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isUsed_);
      }
      if (usedOnOrderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, usedOnOrderId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.CouponProto.Coupon)) {
        return super.equals(obj);
      }
      com.zkart.model.CouponProto.Coupon other = (com.zkart.model.CouponProto.Coupon) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getDateIssued()
          .equals(other.getDateIssued())) return false;
      if (!getValidTill()
          .equals(other.getValidTill())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getIssuedForOrderId()
          != other.getIssuedForOrderId()) return false;
      if (getDiscountPercent()
          != other.getDiscountPercent()) return false;
      if (getIsUsed()
          != other.getIsUsed()) return false;
      if (getUsedOnOrderId()
          != other.getUsedOnOrderId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + DATEISSUED_FIELD_NUMBER;
      hash = (53 * hash) + getDateIssued().hashCode();
      hash = (37 * hash) + VALIDTILL_FIELD_NUMBER;
      hash = (53 * hash) + getValidTill().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + ISSUEDFORORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getIssuedForOrderId();
      hash = (37 * hash) + DISCOUNTPERCENT_FIELD_NUMBER;
      hash = (53 * hash) + getDiscountPercent();
      hash = (37 * hash) + ISUSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsUsed());
      hash = (37 * hash) + USEDONORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getUsedOnOrderId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.CouponProto.Coupon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.CouponProto.Coupon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.CouponProto.Coupon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.CouponProto.Coupon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.CouponProto.Coupon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.CouponProto.Coupon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.CouponProto.Coupon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.CouponProto.Coupon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.CouponProto.Coupon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.CouponProto.Coupon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.CouponProto.Coupon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.CouponProto.Coupon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.CouponProto.Coupon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Coupon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Coupon)
        com.zkart.model.CouponProto.CouponOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.CouponProto.internal_static_Coupon_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.CouponProto.internal_static_Coupon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.CouponProto.Coupon.class, com.zkart.model.CouponProto.Coupon.Builder.class);
      }

      // Construct using com.zkart.model.CouponProto.Coupon.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        dateIssued_ = "";
        validTill_ = "";
        userId_ = 0;
        issuedForOrderId_ = 0;
        discountPercent_ = 0;
        isUsed_ = false;
        usedOnOrderId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.CouponProto.internal_static_Coupon_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.CouponProto.Coupon getDefaultInstanceForType() {
        return com.zkart.model.CouponProto.Coupon.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.CouponProto.Coupon build() {
        com.zkart.model.CouponProto.Coupon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.CouponProto.Coupon buildPartial() {
        com.zkart.model.CouponProto.Coupon result = new com.zkart.model.CouponProto.Coupon(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.zkart.model.CouponProto.Coupon result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dateIssued_ = dateIssued_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.validTill_ = validTill_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.issuedForOrderId_ = issuedForOrderId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.discountPercent_ = discountPercent_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.isUsed_ = isUsed_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.usedOnOrderId_ = usedOnOrderId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.CouponProto.Coupon) {
          return mergeFrom((com.zkart.model.CouponProto.Coupon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.CouponProto.Coupon other) {
        if (other == com.zkart.model.CouponProto.Coupon.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDateIssued().isEmpty()) {
          dateIssued_ = other.dateIssued_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getValidTill().isEmpty()) {
          validTill_ = other.validTill_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getIssuedForOrderId() != 0) {
          setIssuedForOrderId(other.getIssuedForOrderId());
        }
        if (other.getDiscountPercent() != 0) {
          setDiscountPercent(other.getDiscountPercent());
        }
        if (other.getIsUsed() != false) {
          setIsUsed(other.getIsUsed());
        }
        if (other.getUsedOnOrderId() != 0) {
          setUsedOnOrderId(other.getUsedOnOrderId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                dateIssued_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                validTill_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                userId_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                issuedForOrderId_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                discountPercent_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                isUsed_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                usedOnOrderId_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object dateIssued_ = "";
      /**
       * <code>string dateIssued = 2;</code>
       * @return The dateIssued.
       */
      public java.lang.String getDateIssued() {
        java.lang.Object ref = dateIssued_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateIssued_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateIssued = 2;</code>
       * @return The bytes for dateIssued.
       */
      public com.google.protobuf.ByteString
          getDateIssuedBytes() {
        java.lang.Object ref = dateIssued_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateIssued_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateIssued = 2;</code>
       * @param value The dateIssued to set.
       * @return This builder for chaining.
       */
      public Builder setDateIssued(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dateIssued_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string dateIssued = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDateIssued() {
        dateIssued_ = getDefaultInstance().getDateIssued();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string dateIssued = 2;</code>
       * @param value The bytes for dateIssued to set.
       * @return This builder for chaining.
       */
      public Builder setDateIssuedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dateIssued_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object validTill_ = "";
      /**
       * <code>string validTill = 3;</code>
       * @return The validTill.
       */
      public java.lang.String getValidTill() {
        java.lang.Object ref = validTill_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          validTill_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string validTill = 3;</code>
       * @return The bytes for validTill.
       */
      public com.google.protobuf.ByteString
          getValidTillBytes() {
        java.lang.Object ref = validTill_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          validTill_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string validTill = 3;</code>
       * @param value The validTill to set.
       * @return This builder for chaining.
       */
      public Builder setValidTill(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        validTill_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string validTill = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValidTill() {
        validTill_ = getDefaultInstance().getValidTill();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string validTill = 3;</code>
       * @param value The bytes for validTill to set.
       * @return This builder for chaining.
       */
      public Builder setValidTillBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        validTill_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 4;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 4;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {

        userId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = 0;
        onChanged();
        return this;
      }

      private int issuedForOrderId_ ;
      /**
       * <code>int32 issuedForOrderId = 5;</code>
       * @return The issuedForOrderId.
       */
      @java.lang.Override
      public int getIssuedForOrderId() {
        return issuedForOrderId_;
      }
      /**
       * <code>int32 issuedForOrderId = 5;</code>
       * @param value The issuedForOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setIssuedForOrderId(int value) {

        issuedForOrderId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 issuedForOrderId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIssuedForOrderId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        issuedForOrderId_ = 0;
        onChanged();
        return this;
      }

      private int discountPercent_ ;
      /**
       * <code>int32 discountPercent = 6;</code>
       * @return The discountPercent.
       */
      @java.lang.Override
      public int getDiscountPercent() {
        return discountPercent_;
      }
      /**
       * <code>int32 discountPercent = 6;</code>
       * @param value The discountPercent to set.
       * @return This builder for chaining.
       */
      public Builder setDiscountPercent(int value) {

        discountPercent_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 discountPercent = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiscountPercent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        discountPercent_ = 0;
        onChanged();
        return this;
      }

      private boolean isUsed_ ;
      /**
       * <code>bool isUsed = 7;</code>
       * @return The isUsed.
       */
      @java.lang.Override
      public boolean getIsUsed() {
        return isUsed_;
      }
      /**
       * <code>bool isUsed = 7;</code>
       * @param value The isUsed to set.
       * @return This builder for chaining.
       */
      public Builder setIsUsed(boolean value) {

        isUsed_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool isUsed = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsUsed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isUsed_ = false;
        onChanged();
        return this;
      }

      private int usedOnOrderId_ ;
      /**
       * <code>int32 usedOnOrderId = 8;</code>
       * @return The usedOnOrderId.
       */
      @java.lang.Override
      public int getUsedOnOrderId() {
        return usedOnOrderId_;
      }
      /**
       * <code>int32 usedOnOrderId = 8;</code>
       * @param value The usedOnOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setUsedOnOrderId(int value) {

        usedOnOrderId_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int32 usedOnOrderId = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsedOnOrderId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        usedOnOrderId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Coupon)
    }

    // @@protoc_insertion_point(class_scope:Coupon)
    private static final com.zkart.model.CouponProto.Coupon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.CouponProto.Coupon();
    }

    public static com.zkart.model.CouponProto.Coupon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Coupon>
        PARSER = new com.google.protobuf.AbstractParser<Coupon>() {
      @java.lang.Override
      public Coupon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Coupon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Coupon> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.CouponProto.Coupon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CouponsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Coupons)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    java.util.List<com.zkart.model.CouponProto.Coupon> 
        getCouponsList();
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    com.zkart.model.CouponProto.Coupon getCoupons(int index);
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    int getCouponsCount();
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    java.util.List<? extends com.zkart.model.CouponProto.CouponOrBuilder> 
        getCouponsOrBuilderList();
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    com.zkart.model.CouponProto.CouponOrBuilder getCouponsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Coupons}
   */
  public static final class Coupons extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Coupons)
      CouponsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Coupons.class.getName());
    }
    // Use Coupons.newBuilder() to construct.
    private Coupons(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Coupons() {
      coupons_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.CouponProto.internal_static_Coupons_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.CouponProto.internal_static_Coupons_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.CouponProto.Coupons.class, com.zkart.model.CouponProto.Coupons.Builder.class);
    }

    public static final int COUPONS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.zkart.model.CouponProto.Coupon> coupons_;
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.zkart.model.CouponProto.Coupon> getCouponsList() {
      return coupons_;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.zkart.model.CouponProto.CouponOrBuilder> 
        getCouponsOrBuilderList() {
      return coupons_;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    @java.lang.Override
    public int getCouponsCount() {
      return coupons_.size();
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.CouponProto.Coupon getCoupons(int index) {
      return coupons_.get(index);
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.CouponProto.CouponOrBuilder getCouponsOrBuilder(
        int index) {
      return coupons_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < coupons_.size(); i++) {
        output.writeMessage(1, coupons_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < coupons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, coupons_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.CouponProto.Coupons)) {
        return super.equals(obj);
      }
      com.zkart.model.CouponProto.Coupons other = (com.zkart.model.CouponProto.Coupons) obj;

      if (!getCouponsList()
          .equals(other.getCouponsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCouponsCount() > 0) {
        hash = (37 * hash) + COUPONS_FIELD_NUMBER;
        hash = (53 * hash) + getCouponsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.CouponProto.Coupons parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.CouponProto.Coupons parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.CouponProto.Coupons parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.CouponProto.Coupons parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.CouponProto.Coupons parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.CouponProto.Coupons parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.CouponProto.Coupons parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.CouponProto.Coupons parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.CouponProto.Coupons parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.CouponProto.Coupons parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.CouponProto.Coupons parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.CouponProto.Coupons parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.CouponProto.Coupons prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Coupons}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Coupons)
        com.zkart.model.CouponProto.CouponsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.CouponProto.internal_static_Coupons_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.CouponProto.internal_static_Coupons_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.CouponProto.Coupons.class, com.zkart.model.CouponProto.Coupons.Builder.class);
      }

      // Construct using com.zkart.model.CouponProto.Coupons.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (couponsBuilder_ == null) {
          coupons_ = java.util.Collections.emptyList();
        } else {
          coupons_ = null;
          couponsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.CouponProto.internal_static_Coupons_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.CouponProto.Coupons getDefaultInstanceForType() {
        return com.zkart.model.CouponProto.Coupons.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.CouponProto.Coupons build() {
        com.zkart.model.CouponProto.Coupons result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.CouponProto.Coupons buildPartial() {
        com.zkart.model.CouponProto.Coupons result = new com.zkart.model.CouponProto.Coupons(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.zkart.model.CouponProto.Coupons result) {
        if (couponsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            coupons_ = java.util.Collections.unmodifiableList(coupons_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.coupons_ = coupons_;
        } else {
          result.coupons_ = couponsBuilder_.build();
        }
      }

      private void buildPartial0(com.zkart.model.CouponProto.Coupons result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.CouponProto.Coupons) {
          return mergeFrom((com.zkart.model.CouponProto.Coupons)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.CouponProto.Coupons other) {
        if (other == com.zkart.model.CouponProto.Coupons.getDefaultInstance()) return this;
        if (couponsBuilder_ == null) {
          if (!other.coupons_.isEmpty()) {
            if (coupons_.isEmpty()) {
              coupons_ = other.coupons_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCouponsIsMutable();
              coupons_.addAll(other.coupons_);
            }
            onChanged();
          }
        } else {
          if (!other.coupons_.isEmpty()) {
            if (couponsBuilder_.isEmpty()) {
              couponsBuilder_.dispose();
              couponsBuilder_ = null;
              coupons_ = other.coupons_;
              bitField0_ = (bitField0_ & ~0x00000001);
              couponsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCouponsFieldBuilder() : null;
            } else {
              couponsBuilder_.addAllMessages(other.coupons_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.zkart.model.CouponProto.Coupon m =
                    input.readMessage(
                        com.zkart.model.CouponProto.Coupon.parser(),
                        extensionRegistry);
                if (couponsBuilder_ == null) {
                  ensureCouponsIsMutable();
                  coupons_.add(m);
                } else {
                  couponsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zkart.model.CouponProto.Coupon> coupons_ =
        java.util.Collections.emptyList();
      private void ensureCouponsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          coupons_ = new java.util.ArrayList<com.zkart.model.CouponProto.Coupon>(coupons_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.CouponProto.Coupon, com.zkart.model.CouponProto.Coupon.Builder, com.zkart.model.CouponProto.CouponOrBuilder> couponsBuilder_;

      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public java.util.List<com.zkart.model.CouponProto.Coupon> getCouponsList() {
        if (couponsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(coupons_);
        } else {
          return couponsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public int getCouponsCount() {
        if (couponsBuilder_ == null) {
          return coupons_.size();
        } else {
          return couponsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public com.zkart.model.CouponProto.Coupon getCoupons(int index) {
        if (couponsBuilder_ == null) {
          return coupons_.get(index);
        } else {
          return couponsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public Builder setCoupons(
          int index, com.zkart.model.CouponProto.Coupon value) {
        if (couponsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponsIsMutable();
          coupons_.set(index, value);
          onChanged();
        } else {
          couponsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public Builder setCoupons(
          int index, com.zkart.model.CouponProto.Coupon.Builder builderForValue) {
        if (couponsBuilder_ == null) {
          ensureCouponsIsMutable();
          coupons_.set(index, builderForValue.build());
          onChanged();
        } else {
          couponsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public Builder addCoupons(com.zkart.model.CouponProto.Coupon value) {
        if (couponsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponsIsMutable();
          coupons_.add(value);
          onChanged();
        } else {
          couponsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public Builder addCoupons(
          int index, com.zkart.model.CouponProto.Coupon value) {
        if (couponsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCouponsIsMutable();
          coupons_.add(index, value);
          onChanged();
        } else {
          couponsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public Builder addCoupons(
          com.zkart.model.CouponProto.Coupon.Builder builderForValue) {
        if (couponsBuilder_ == null) {
          ensureCouponsIsMutable();
          coupons_.add(builderForValue.build());
          onChanged();
        } else {
          couponsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public Builder addCoupons(
          int index, com.zkart.model.CouponProto.Coupon.Builder builderForValue) {
        if (couponsBuilder_ == null) {
          ensureCouponsIsMutable();
          coupons_.add(index, builderForValue.build());
          onChanged();
        } else {
          couponsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public Builder addAllCoupons(
          java.lang.Iterable<? extends com.zkart.model.CouponProto.Coupon> values) {
        if (couponsBuilder_ == null) {
          ensureCouponsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, coupons_);
          onChanged();
        } else {
          couponsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public Builder clearCoupons() {
        if (couponsBuilder_ == null) {
          coupons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          couponsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public Builder removeCoupons(int index) {
        if (couponsBuilder_ == null) {
          ensureCouponsIsMutable();
          coupons_.remove(index);
          onChanged();
        } else {
          couponsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public com.zkart.model.CouponProto.Coupon.Builder getCouponsBuilder(
          int index) {
        return getCouponsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public com.zkart.model.CouponProto.CouponOrBuilder getCouponsOrBuilder(
          int index) {
        if (couponsBuilder_ == null) {
          return coupons_.get(index);  } else {
          return couponsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public java.util.List<? extends com.zkart.model.CouponProto.CouponOrBuilder> 
           getCouponsOrBuilderList() {
        if (couponsBuilder_ != null) {
          return couponsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(coupons_);
        }
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public com.zkart.model.CouponProto.Coupon.Builder addCouponsBuilder() {
        return getCouponsFieldBuilder().addBuilder(
            com.zkart.model.CouponProto.Coupon.getDefaultInstance());
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public com.zkart.model.CouponProto.Coupon.Builder addCouponsBuilder(
          int index) {
        return getCouponsFieldBuilder().addBuilder(
            index, com.zkart.model.CouponProto.Coupon.getDefaultInstance());
      }
      /**
       * <code>repeated .Coupon coupons = 1;</code>
       */
      public java.util.List<com.zkart.model.CouponProto.Coupon.Builder> 
           getCouponsBuilderList() {
        return getCouponsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.CouponProto.Coupon, com.zkart.model.CouponProto.Coupon.Builder, com.zkart.model.CouponProto.CouponOrBuilder> 
          getCouponsFieldBuilder() {
        if (couponsBuilder_ == null) {
          couponsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zkart.model.CouponProto.Coupon, com.zkart.model.CouponProto.Coupon.Builder, com.zkart.model.CouponProto.CouponOrBuilder>(
                  coupons_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          coupons_ = null;
        }
        return couponsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Coupons)
    }

    // @@protoc_insertion_point(class_scope:Coupons)
    private static final com.zkart.model.CouponProto.Coupons DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.CouponProto.Coupons();
    }

    public static com.zkart.model.CouponProto.Coupons getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Coupons>
        PARSER = new com.google.protobuf.AbstractParser<Coupons>() {
      @java.lang.Override
      public Coupons parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Coupons> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Coupons> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.CouponProto.Coupons getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Coupon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Coupon_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Coupons_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Coupons_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$com/zkart/dbFiles/proto/coupon.proto\"\245" +
      "\001\n\006Coupon\022\n\n\002id\030\001 \001(\t\022\022\n\ndateIssued\030\002 \001(" +
      "\t\022\021\n\tvalidTill\030\003 \001(\t\022\016\n\006userId\030\004 \001(\005\022\030\n\020" +
      "issuedForOrderId\030\005 \001(\005\022\027\n\017discountPercen" +
      "t\030\006 \001(\005\022\016\n\006isUsed\030\007 \001(\010\022\025\n\rusedOnOrderId" +
      "\030\010 \001(\005\"#\n\007Coupons\022\030\n\007coupons\030\001 \003(\0132\007.Cou" +
      "ponB\036\n\017com.zkart.modelB\013CouponProtob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Coupon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Coupon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Coupon_descriptor,
        new java.lang.String[] { "Id", "DateIssued", "ValidTill", "UserId", "IssuedForOrderId", "DiscountPercent", "IsUsed", "UsedOnOrderId", });
    internal_static_Coupons_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Coupons_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Coupons_descriptor,
        new java.lang.String[] { "Coupons", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
