// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/zkart/dbFiles/proto/order.proto
// Protobuf Java Version: 4.29.3

package com.zkart.model;

public final class OrderProto {
  private OrderProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      OrderProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 userId = 4;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>int32 totalPrice = 2;</code>
     * @return The totalPrice.
     */
    int getTotalPrice();

    /**
     * <code>repeated int32 productIds = 3;</code>
     * @return A list containing the productIds.
     */
    java.util.List<java.lang.Integer> getProductIdsList();
    /**
     * <code>repeated int32 productIds = 3;</code>
     * @return The count of productIds.
     */
    int getProductIdsCount();
    /**
     * <code>repeated int32 productIds = 3;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    int getProductIds(int index);
  }
  /**
   * Protobuf type {@code Order}
   */
  public static final class Order extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Order.class.getName());
    }
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      productIds_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.OrderProto.internal_static_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.OrderProto.internal_static_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.OrderProto.Order.class, com.zkart.model.OrderProto.Order.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private int userId_ = 0;
    /**
     * <code>int32 userId = 4;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int TOTALPRICE_FIELD_NUMBER = 2;
    private int totalPrice_ = 0;
    /**
     * <code>int32 totalPrice = 2;</code>
     * @return The totalPrice.
     */
    @java.lang.Override
    public int getTotalPrice() {
      return totalPrice_;
    }

    public static final int PRODUCTIDS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList productIds_ =
        emptyIntList();
    /**
     * <code>repeated int32 productIds = 3;</code>
     * @return A list containing the productIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getProductIdsList() {
      return productIds_;
    }
    /**
     * <code>repeated int32 productIds = 3;</code>
     * @return The count of productIds.
     */
    public int getProductIdsCount() {
      return productIds_.size();
    }
    /**
     * <code>repeated int32 productIds = 3;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    public int getProductIds(int index) {
      return productIds_.getInt(index);
    }
    private int productIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (totalPrice_ != 0) {
        output.writeInt32(2, totalPrice_);
      }
      if (getProductIdsList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(productIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < productIds_.size(); i++) {
        output.writeInt32NoTag(productIds_.getInt(i));
      }
      if (userId_ != 0) {
        output.writeInt32(4, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (totalPrice_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalPrice_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < productIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(productIds_.getInt(i));
        }
        size += dataSize;
        if (!getProductIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        productIdsMemoizedSerializedSize = dataSize;
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.OrderProto.Order)) {
        return super.equals(obj);
      }
      com.zkart.model.OrderProto.Order other = (com.zkart.model.OrderProto.Order) obj;

      if (getId()
          != other.getId()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getTotalPrice()
          != other.getTotalPrice()) return false;
      if (!getProductIdsList()
          .equals(other.getProductIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + TOTALPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPrice();
      if (getProductIdsCount() > 0) {
        hash = (37 * hash) + PRODUCTIDS_FIELD_NUMBER;
        hash = (53 * hash) + getProductIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.OrderProto.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.OrderProto.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.OrderProto.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.OrderProto.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Order)
        com.zkart.model.OrderProto.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.OrderProto.internal_static_Order_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.OrderProto.internal_static_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.OrderProto.Order.class, com.zkart.model.OrderProto.Order.Builder.class);
      }

      // Construct using com.zkart.model.OrderProto.Order.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        userId_ = 0;
        totalPrice_ = 0;
        productIds_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.OrderProto.internal_static_Order_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Order getDefaultInstanceForType() {
        return com.zkart.model.OrderProto.Order.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Order build() {
        com.zkart.model.OrderProto.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Order buildPartial() {
        com.zkart.model.OrderProto.Order result = new com.zkart.model.OrderProto.Order(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.zkart.model.OrderProto.Order result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalPrice_ = totalPrice_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          productIds_.makeImmutable();
          result.productIds_ = productIds_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.OrderProto.Order) {
          return mergeFrom((com.zkart.model.OrderProto.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.OrderProto.Order other) {
        if (other == com.zkart.model.OrderProto.Order.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getTotalPrice() != 0) {
          setTotalPrice(other.getTotalPrice());
        }
        if (!other.productIds_.isEmpty()) {
          if (productIds_.isEmpty()) {
            productIds_ = other.productIds_;
            productIds_.makeImmutable();
            bitField0_ |= 0x00000008;
          } else {
            ensureProductIdsIsMutable();
            productIds_.addAll(other.productIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                totalPrice_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 16
              case 24: {
                int v = input.readInt32();
                ensureProductIdsIsMutable();
                productIds_.addInt(v);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureProductIdsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  productIds_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 32: {
                userId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 4;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 4;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {

        userId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      private int totalPrice_ ;
      /**
       * <code>int32 totalPrice = 2;</code>
       * @return The totalPrice.
       */
      @java.lang.Override
      public int getTotalPrice() {
        return totalPrice_;
      }
      /**
       * <code>int32 totalPrice = 2;</code>
       * @param value The totalPrice to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPrice(int value) {

        totalPrice_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalPrice = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalPrice_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList productIds_ = emptyIntList();
      private void ensureProductIdsIsMutable() {
        if (!productIds_.isModifiable()) {
          productIds_ = makeMutableCopy(productIds_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated int32 productIds = 3;</code>
       * @return A list containing the productIds.
       */
      public java.util.List<java.lang.Integer>
          getProductIdsList() {
        productIds_.makeImmutable();
        return productIds_;
      }
      /**
       * <code>repeated int32 productIds = 3;</code>
       * @return The count of productIds.
       */
      public int getProductIdsCount() {
        return productIds_.size();
      }
      /**
       * <code>repeated int32 productIds = 3;</code>
       * @param index The index of the element to return.
       * @return The productIds at the given index.
       */
      public int getProductIds(int index) {
        return productIds_.getInt(index);
      }
      /**
       * <code>repeated int32 productIds = 3;</code>
       * @param index The index to set the value at.
       * @param value The productIds to set.
       * @return This builder for chaining.
       */
      public Builder setProductIds(
          int index, int value) {

        ensureProductIdsIsMutable();
        productIds_.setInt(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 productIds = 3;</code>
       * @param value The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addProductIds(int value) {

        ensureProductIdsIsMutable();
        productIds_.addInt(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 productIds = 3;</code>
       * @param values The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllProductIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureProductIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productIds_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 productIds = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductIds() {
        productIds_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Order)
    }

    // @@protoc_insertion_point(class_scope:Order)
    private static final com.zkart.model.OrderProto.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.OrderProto.Order();
    }

    public static com.zkart.model.OrderProto.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      @java.lang.Override
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.OrderProto.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrdersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Orders)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Order orders = 1;</code>
     */
    java.util.List<com.zkart.model.OrderProto.Order> 
        getOrdersList();
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    com.zkart.model.OrderProto.Order getOrders(int index);
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    int getOrdersCount();
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    java.util.List<? extends com.zkart.model.OrderProto.OrderOrBuilder> 
        getOrdersOrBuilderList();
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    com.zkart.model.OrderProto.OrderOrBuilder getOrdersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Orders}
   */
  public static final class Orders extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Orders)
      OrdersOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Orders.class.getName());
    }
    // Use Orders.newBuilder() to construct.
    private Orders(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Orders() {
      orders_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.OrderProto.internal_static_Orders_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.OrderProto.internal_static_Orders_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.OrderProto.Orders.class, com.zkart.model.OrderProto.Orders.Builder.class);
    }

    public static final int ORDERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.zkart.model.OrderProto.Order> orders_;
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.zkart.model.OrderProto.Order> getOrdersList() {
      return orders_;
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.zkart.model.OrderProto.OrderOrBuilder> 
        getOrdersOrBuilderList() {
      return orders_;
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public int getOrdersCount() {
      return orders_.size();
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.OrderProto.Order getOrders(int index) {
      return orders_.get(index);
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.OrderProto.OrderOrBuilder getOrdersOrBuilder(
        int index) {
      return orders_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < orders_.size(); i++) {
        output.writeMessage(1, orders_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < orders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, orders_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.OrderProto.Orders)) {
        return super.equals(obj);
      }
      com.zkart.model.OrderProto.Orders other = (com.zkart.model.OrderProto.Orders) obj;

      if (!getOrdersList()
          .equals(other.getOrdersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOrdersCount() > 0) {
        hash = (37 * hash) + ORDERS_FIELD_NUMBER;
        hash = (53 * hash) + getOrdersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.OrderProto.Orders parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.OrderProto.Orders parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.OrderProto.Orders parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.OrderProto.Orders prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Orders}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Orders)
        com.zkart.model.OrderProto.OrdersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.OrderProto.internal_static_Orders_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.OrderProto.internal_static_Orders_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.OrderProto.Orders.class, com.zkart.model.OrderProto.Orders.Builder.class);
      }

      // Construct using com.zkart.model.OrderProto.Orders.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
        } else {
          orders_ = null;
          ordersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.OrderProto.internal_static_Orders_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Orders getDefaultInstanceForType() {
        return com.zkart.model.OrderProto.Orders.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Orders build() {
        com.zkart.model.OrderProto.Orders result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Orders buildPartial() {
        com.zkart.model.OrderProto.Orders result = new com.zkart.model.OrderProto.Orders(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.zkart.model.OrderProto.Orders result) {
        if (ordersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            orders_ = java.util.Collections.unmodifiableList(orders_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.orders_ = orders_;
        } else {
          result.orders_ = ordersBuilder_.build();
        }
      }

      private void buildPartial0(com.zkart.model.OrderProto.Orders result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.OrderProto.Orders) {
          return mergeFrom((com.zkart.model.OrderProto.Orders)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.OrderProto.Orders other) {
        if (other == com.zkart.model.OrderProto.Orders.getDefaultInstance()) return this;
        if (ordersBuilder_ == null) {
          if (!other.orders_.isEmpty()) {
            if (orders_.isEmpty()) {
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrdersIsMutable();
              orders_.addAll(other.orders_);
            }
            onChanged();
          }
        } else {
          if (!other.orders_.isEmpty()) {
            if (ordersBuilder_.isEmpty()) {
              ordersBuilder_.dispose();
              ordersBuilder_ = null;
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ordersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOrdersFieldBuilder() : null;
            } else {
              ordersBuilder_.addAllMessages(other.orders_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.zkart.model.OrderProto.Order m =
                    input.readMessage(
                        com.zkart.model.OrderProto.Order.parser(),
                        extensionRegistry);
                if (ordersBuilder_ == null) {
                  ensureOrdersIsMutable();
                  orders_.add(m);
                } else {
                  ordersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zkart.model.OrderProto.Order> orders_ =
        java.util.Collections.emptyList();
      private void ensureOrdersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          orders_ = new java.util.ArrayList<com.zkart.model.OrderProto.Order>(orders_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.OrderProto.Order, com.zkart.model.OrderProto.Order.Builder, com.zkart.model.OrderProto.OrderOrBuilder> ordersBuilder_;

      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public java.util.List<com.zkart.model.OrderProto.Order> getOrdersList() {
        if (ordersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orders_);
        } else {
          return ordersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public int getOrdersCount() {
        if (ordersBuilder_ == null) {
          return orders_.size();
        } else {
          return ordersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.Order getOrders(int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);
        } else {
          return ordersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder setOrders(
          int index, com.zkart.model.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.set(index, value);
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder setOrders(
          int index, com.zkart.model.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.set(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(com.zkart.model.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(
          int index, com.zkart.model.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(index, value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(
          com.zkart.model.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(
          int index, com.zkart.model.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addAllOrders(
          java.lang.Iterable<? extends com.zkart.model.OrderProto.Order> values) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orders_);
          onChanged();
        } else {
          ordersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder clearOrders() {
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ordersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder removeOrders(int index) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.remove(index);
          onChanged();
        } else {
          ordersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.Order.Builder getOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.OrderOrBuilder getOrdersOrBuilder(
          int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);  } else {
          return ordersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public java.util.List<? extends com.zkart.model.OrderProto.OrderOrBuilder> 
           getOrdersOrBuilderList() {
        if (ordersBuilder_ != null) {
          return ordersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orders_);
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.Order.Builder addOrdersBuilder() {
        return getOrdersFieldBuilder().addBuilder(
            com.zkart.model.OrderProto.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.Order.Builder addOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().addBuilder(
            index, com.zkart.model.OrderProto.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public java.util.List<com.zkart.model.OrderProto.Order.Builder> 
           getOrdersBuilderList() {
        return getOrdersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.OrderProto.Order, com.zkart.model.OrderProto.Order.Builder, com.zkart.model.OrderProto.OrderOrBuilder> 
          getOrdersFieldBuilder() {
        if (ordersBuilder_ == null) {
          ordersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zkart.model.OrderProto.Order, com.zkart.model.OrderProto.Order.Builder, com.zkart.model.OrderProto.OrderOrBuilder>(
                  orders_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          orders_ = null;
        }
        return ordersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Orders)
    }

    // @@protoc_insertion_point(class_scope:Orders)
    private static final com.zkart.model.OrderProto.Orders DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.OrderProto.Orders();
    }

    public static com.zkart.model.OrderProto.Orders getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Orders>
        PARSER = new com.google.protobuf.AbstractParser<Orders>() {
      @java.lang.Override
      public Orders parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Orders> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Orders> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.OrderProto.Orders getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Orders_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Orders_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#com/zkart/dbFiles/proto/order.proto\"K\n" +
      "\005Order\022\n\n\002id\030\001 \001(\005\022\016\n\006userId\030\004 \001(\005\022\022\n\nto" +
      "talPrice\030\002 \001(\005\022\022\n\nproductIds\030\003 \003(\005\" \n\006Or" +
      "ders\022\026\n\006orders\030\001 \003(\0132\006.OrderB\035\n\017com.zkar" +
      "t.modelB\nOrderProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "Id", "UserId", "TotalPrice", "ProductIds", });
    internal_static_Orders_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Orders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Orders_descriptor,
        new java.lang.String[] { "Orders", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
