// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/zkart/dbFiles/proto/order.proto
// Protobuf Java Version: 4.29.3

package com.zkart.model;

public final class OrderProto {
  private OrderProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      OrderProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 userId = 2;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>int32 totalPrice = 3;</code>
     * @return The totalPrice.
     */
    int getTotalPrice();

    /**
     * <code>bool isCouponApplied = 4;</code>
     * @return The isCouponApplied.
     */
    boolean getIsCouponApplied();

    /**
     * <code>string couponCode = 5;</code>
     * @return The couponCode.
     */
    java.lang.String getCouponCode();
    /**
     * <code>string couponCode = 5;</code>
     * @return The bytes for couponCode.
     */
    com.google.protobuf.ByteString
        getCouponCodeBytes();

    /**
     * <code>int32 discountPercent = 6;</code>
     * @return The discountPercent.
     */
    int getDiscountPercent();

    /**
     * <code>int32 finalPrice = 7;</code>
     * @return The finalPrice.
     */
    int getFinalPrice();

    /**
     * <code>string timeStamps = 8;</code>
     * @return The timeStamps.
     */
    java.lang.String getTimeStamps();
    /**
     * <code>string timeStamps = 8;</code>
     * @return The bytes for timeStamps.
     */
    com.google.protobuf.ByteString
        getTimeStampsBytes();

    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    java.util.List<com.zkart.model.OrderProto.ProductDetails> 
        getProductDetailsListList();
    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    com.zkart.model.OrderProto.ProductDetails getProductDetailsList(int index);
    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    int getProductDetailsListCount();
    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    java.util.List<? extends com.zkart.model.OrderProto.ProductDetailsOrBuilder> 
        getProductDetailsListOrBuilderList();
    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    com.zkart.model.OrderProto.ProductDetailsOrBuilder getProductDetailsListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Order}
   */
  public static final class Order extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Order.class.getName());
    }
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      couponCode_ = "";
      timeStamps_ = "";
      productDetailsList_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.OrderProto.internal_static_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.OrderProto.internal_static_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.OrderProto.Order.class, com.zkart.model.OrderProto.Order.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_ = 0;
    /**
     * <code>int32 userId = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int TOTALPRICE_FIELD_NUMBER = 3;
    private int totalPrice_ = 0;
    /**
     * <code>int32 totalPrice = 3;</code>
     * @return The totalPrice.
     */
    @java.lang.Override
    public int getTotalPrice() {
      return totalPrice_;
    }

    public static final int ISCOUPONAPPLIED_FIELD_NUMBER = 4;
    private boolean isCouponApplied_ = false;
    /**
     * <code>bool isCouponApplied = 4;</code>
     * @return The isCouponApplied.
     */
    @java.lang.Override
    public boolean getIsCouponApplied() {
      return isCouponApplied_;
    }

    public static final int COUPONCODE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object couponCode_ = "";
    /**
     * <code>string couponCode = 5;</code>
     * @return The couponCode.
     */
    @java.lang.Override
    public java.lang.String getCouponCode() {
      java.lang.Object ref = couponCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        couponCode_ = s;
        return s;
      }
    }
    /**
     * <code>string couponCode = 5;</code>
     * @return The bytes for couponCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCouponCodeBytes() {
      java.lang.Object ref = couponCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        couponCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISCOUNTPERCENT_FIELD_NUMBER = 6;
    private int discountPercent_ = 0;
    /**
     * <code>int32 discountPercent = 6;</code>
     * @return The discountPercent.
     */
    @java.lang.Override
    public int getDiscountPercent() {
      return discountPercent_;
    }

    public static final int FINALPRICE_FIELD_NUMBER = 7;
    private int finalPrice_ = 0;
    /**
     * <code>int32 finalPrice = 7;</code>
     * @return The finalPrice.
     */
    @java.lang.Override
    public int getFinalPrice() {
      return finalPrice_;
    }

    public static final int TIMESTAMPS_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object timeStamps_ = "";
    /**
     * <code>string timeStamps = 8;</code>
     * @return The timeStamps.
     */
    @java.lang.Override
    public java.lang.String getTimeStamps() {
      java.lang.Object ref = timeStamps_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStamps_ = s;
        return s;
      }
    }
    /**
     * <code>string timeStamps = 8;</code>
     * @return The bytes for timeStamps.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeStampsBytes() {
      java.lang.Object ref = timeStamps_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamps_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTDETAILSLIST_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private java.util.List<com.zkart.model.OrderProto.ProductDetails> productDetailsList_;
    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    @java.lang.Override
    public java.util.List<com.zkart.model.OrderProto.ProductDetails> getProductDetailsListList() {
      return productDetailsList_;
    }
    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.zkart.model.OrderProto.ProductDetailsOrBuilder> 
        getProductDetailsListOrBuilderList() {
      return productDetailsList_;
    }
    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    @java.lang.Override
    public int getProductDetailsListCount() {
      return productDetailsList_.size();
    }
    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    @java.lang.Override
    public com.zkart.model.OrderProto.ProductDetails getProductDetailsList(int index) {
      return productDetailsList_.get(index);
    }
    /**
     * <code>repeated .ProductDetails productDetailsList = 9;</code>
     */
    @java.lang.Override
    public com.zkart.model.OrderProto.ProductDetailsOrBuilder getProductDetailsListOrBuilder(
        int index) {
      return productDetailsList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (totalPrice_ != 0) {
        output.writeInt32(3, totalPrice_);
      }
      if (isCouponApplied_ != false) {
        output.writeBool(4, isCouponApplied_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(couponCode_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, couponCode_);
      }
      if (discountPercent_ != 0) {
        output.writeInt32(6, discountPercent_);
      }
      if (finalPrice_ != 0) {
        output.writeInt32(7, finalPrice_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timeStamps_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, timeStamps_);
      }
      for (int i = 0; i < productDetailsList_.size(); i++) {
        output.writeMessage(9, productDetailsList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (totalPrice_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalPrice_);
      }
      if (isCouponApplied_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isCouponApplied_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(couponCode_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, couponCode_);
      }
      if (discountPercent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, discountPercent_);
      }
      if (finalPrice_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, finalPrice_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timeStamps_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, timeStamps_);
      }
      for (int i = 0; i < productDetailsList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, productDetailsList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.OrderProto.Order)) {
        return super.equals(obj);
      }
      com.zkart.model.OrderProto.Order other = (com.zkart.model.OrderProto.Order) obj;

      if (getId()
          != other.getId()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getTotalPrice()
          != other.getTotalPrice()) return false;
      if (getIsCouponApplied()
          != other.getIsCouponApplied()) return false;
      if (!getCouponCode()
          .equals(other.getCouponCode())) return false;
      if (getDiscountPercent()
          != other.getDiscountPercent()) return false;
      if (getFinalPrice()
          != other.getFinalPrice()) return false;
      if (!getTimeStamps()
          .equals(other.getTimeStamps())) return false;
      if (!getProductDetailsListList()
          .equals(other.getProductDetailsListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + TOTALPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPrice();
      hash = (37 * hash) + ISCOUPONAPPLIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsCouponApplied());
      hash = (37 * hash) + COUPONCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCouponCode().hashCode();
      hash = (37 * hash) + DISCOUNTPERCENT_FIELD_NUMBER;
      hash = (53 * hash) + getDiscountPercent();
      hash = (37 * hash) + FINALPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getFinalPrice();
      hash = (37 * hash) + TIMESTAMPS_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamps().hashCode();
      if (getProductDetailsListCount() > 0) {
        hash = (37 * hash) + PRODUCTDETAILSLIST_FIELD_NUMBER;
        hash = (53 * hash) + getProductDetailsListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.OrderProto.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.OrderProto.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.OrderProto.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.OrderProto.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Order)
        com.zkart.model.OrderProto.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.OrderProto.internal_static_Order_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.OrderProto.internal_static_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.OrderProto.Order.class, com.zkart.model.OrderProto.Order.Builder.class);
      }

      // Construct using com.zkart.model.OrderProto.Order.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        userId_ = 0;
        totalPrice_ = 0;
        isCouponApplied_ = false;
        couponCode_ = "";
        discountPercent_ = 0;
        finalPrice_ = 0;
        timeStamps_ = "";
        if (productDetailsListBuilder_ == null) {
          productDetailsList_ = java.util.Collections.emptyList();
        } else {
          productDetailsList_ = null;
          productDetailsListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.OrderProto.internal_static_Order_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Order getDefaultInstanceForType() {
        return com.zkart.model.OrderProto.Order.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Order build() {
        com.zkart.model.OrderProto.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Order buildPartial() {
        com.zkart.model.OrderProto.Order result = new com.zkart.model.OrderProto.Order(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.zkart.model.OrderProto.Order result) {
        if (productDetailsListBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0)) {
            productDetailsList_ = java.util.Collections.unmodifiableList(productDetailsList_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.productDetailsList_ = productDetailsList_;
        } else {
          result.productDetailsList_ = productDetailsListBuilder_.build();
        }
      }

      private void buildPartial0(com.zkart.model.OrderProto.Order result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalPrice_ = totalPrice_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.isCouponApplied_ = isCouponApplied_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.couponCode_ = couponCode_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.discountPercent_ = discountPercent_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.finalPrice_ = finalPrice_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.timeStamps_ = timeStamps_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.OrderProto.Order) {
          return mergeFrom((com.zkart.model.OrderProto.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.OrderProto.Order other) {
        if (other == com.zkart.model.OrderProto.Order.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getTotalPrice() != 0) {
          setTotalPrice(other.getTotalPrice());
        }
        if (other.getIsCouponApplied() != false) {
          setIsCouponApplied(other.getIsCouponApplied());
        }
        if (!other.getCouponCode().isEmpty()) {
          couponCode_ = other.couponCode_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getDiscountPercent() != 0) {
          setDiscountPercent(other.getDiscountPercent());
        }
        if (other.getFinalPrice() != 0) {
          setFinalPrice(other.getFinalPrice());
        }
        if (!other.getTimeStamps().isEmpty()) {
          timeStamps_ = other.timeStamps_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (productDetailsListBuilder_ == null) {
          if (!other.productDetailsList_.isEmpty()) {
            if (productDetailsList_.isEmpty()) {
              productDetailsList_ = other.productDetailsList_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureProductDetailsListIsMutable();
              productDetailsList_.addAll(other.productDetailsList_);
            }
            onChanged();
          }
        } else {
          if (!other.productDetailsList_.isEmpty()) {
            if (productDetailsListBuilder_.isEmpty()) {
              productDetailsListBuilder_.dispose();
              productDetailsListBuilder_ = null;
              productDetailsList_ = other.productDetailsList_;
              bitField0_ = (bitField0_ & ~0x00000100);
              productDetailsListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProductDetailsListFieldBuilder() : null;
            } else {
              productDetailsListBuilder_.addAllMessages(other.productDetailsList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                userId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                totalPrice_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                isCouponApplied_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                couponCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                discountPercent_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                finalPrice_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                timeStamps_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                com.zkart.model.OrderProto.ProductDetails m =
                    input.readMessage(
                        com.zkart.model.OrderProto.ProductDetails.parser(),
                        extensionRegistry);
                if (productDetailsListBuilder_ == null) {
                  ensureProductDetailsListIsMutable();
                  productDetailsList_.add(m);
                } else {
                  productDetailsListBuilder_.addMessage(m);
                }
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 2;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {

        userId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      private int totalPrice_ ;
      /**
       * <code>int32 totalPrice = 3;</code>
       * @return The totalPrice.
       */
      @java.lang.Override
      public int getTotalPrice() {
        return totalPrice_;
      }
      /**
       * <code>int32 totalPrice = 3;</code>
       * @param value The totalPrice to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPrice(int value) {

        totalPrice_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalPrice = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalPrice_ = 0;
        onChanged();
        return this;
      }

      private boolean isCouponApplied_ ;
      /**
       * <code>bool isCouponApplied = 4;</code>
       * @return The isCouponApplied.
       */
      @java.lang.Override
      public boolean getIsCouponApplied() {
        return isCouponApplied_;
      }
      /**
       * <code>bool isCouponApplied = 4;</code>
       * @param value The isCouponApplied to set.
       * @return This builder for chaining.
       */
      public Builder setIsCouponApplied(boolean value) {

        isCouponApplied_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool isCouponApplied = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsCouponApplied() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isCouponApplied_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object couponCode_ = "";
      /**
       * <code>string couponCode = 5;</code>
       * @return The couponCode.
       */
      public java.lang.String getCouponCode() {
        java.lang.Object ref = couponCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          couponCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string couponCode = 5;</code>
       * @return The bytes for couponCode.
       */
      public com.google.protobuf.ByteString
          getCouponCodeBytes() {
        java.lang.Object ref = couponCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          couponCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string couponCode = 5;</code>
       * @param value The couponCode to set.
       * @return This builder for chaining.
       */
      public Builder setCouponCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        couponCode_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string couponCode = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCouponCode() {
        couponCode_ = getDefaultInstance().getCouponCode();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string couponCode = 5;</code>
       * @param value The bytes for couponCode to set.
       * @return This builder for chaining.
       */
      public Builder setCouponCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        couponCode_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int discountPercent_ ;
      /**
       * <code>int32 discountPercent = 6;</code>
       * @return The discountPercent.
       */
      @java.lang.Override
      public int getDiscountPercent() {
        return discountPercent_;
      }
      /**
       * <code>int32 discountPercent = 6;</code>
       * @param value The discountPercent to set.
       * @return This builder for chaining.
       */
      public Builder setDiscountPercent(int value) {

        discountPercent_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 discountPercent = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiscountPercent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        discountPercent_ = 0;
        onChanged();
        return this;
      }

      private int finalPrice_ ;
      /**
       * <code>int32 finalPrice = 7;</code>
       * @return The finalPrice.
       */
      @java.lang.Override
      public int getFinalPrice() {
        return finalPrice_;
      }
      /**
       * <code>int32 finalPrice = 7;</code>
       * @param value The finalPrice to set.
       * @return This builder for chaining.
       */
      public Builder setFinalPrice(int value) {

        finalPrice_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 finalPrice = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFinalPrice() {
        bitField0_ = (bitField0_ & ~0x00000040);
        finalPrice_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object timeStamps_ = "";
      /**
       * <code>string timeStamps = 8;</code>
       * @return The timeStamps.
       */
      public java.lang.String getTimeStamps() {
        java.lang.Object ref = timeStamps_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeStamps_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timeStamps = 8;</code>
       * @return The bytes for timeStamps.
       */
      public com.google.protobuf.ByteString
          getTimeStampsBytes() {
        java.lang.Object ref = timeStamps_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamps_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timeStamps = 8;</code>
       * @param value The timeStamps to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamps(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        timeStamps_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string timeStamps = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamps() {
        timeStamps_ = getDefaultInstance().getTimeStamps();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string timeStamps = 8;</code>
       * @param value The bytes for timeStamps to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStampsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        timeStamps_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.util.List<com.zkart.model.OrderProto.ProductDetails> productDetailsList_ =
        java.util.Collections.emptyList();
      private void ensureProductDetailsListIsMutable() {
        if (!((bitField0_ & 0x00000100) != 0)) {
          productDetailsList_ = new java.util.ArrayList<com.zkart.model.OrderProto.ProductDetails>(productDetailsList_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.OrderProto.ProductDetails, com.zkart.model.OrderProto.ProductDetails.Builder, com.zkart.model.OrderProto.ProductDetailsOrBuilder> productDetailsListBuilder_;

      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public java.util.List<com.zkart.model.OrderProto.ProductDetails> getProductDetailsListList() {
        if (productDetailsListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(productDetailsList_);
        } else {
          return productDetailsListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public int getProductDetailsListCount() {
        if (productDetailsListBuilder_ == null) {
          return productDetailsList_.size();
        } else {
          return productDetailsListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public com.zkart.model.OrderProto.ProductDetails getProductDetailsList(int index) {
        if (productDetailsListBuilder_ == null) {
          return productDetailsList_.get(index);
        } else {
          return productDetailsListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public Builder setProductDetailsList(
          int index, com.zkart.model.OrderProto.ProductDetails value) {
        if (productDetailsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductDetailsListIsMutable();
          productDetailsList_.set(index, value);
          onChanged();
        } else {
          productDetailsListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public Builder setProductDetailsList(
          int index, com.zkart.model.OrderProto.ProductDetails.Builder builderForValue) {
        if (productDetailsListBuilder_ == null) {
          ensureProductDetailsListIsMutable();
          productDetailsList_.set(index, builderForValue.build());
          onChanged();
        } else {
          productDetailsListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public Builder addProductDetailsList(com.zkart.model.OrderProto.ProductDetails value) {
        if (productDetailsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductDetailsListIsMutable();
          productDetailsList_.add(value);
          onChanged();
        } else {
          productDetailsListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public Builder addProductDetailsList(
          int index, com.zkart.model.OrderProto.ProductDetails value) {
        if (productDetailsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductDetailsListIsMutable();
          productDetailsList_.add(index, value);
          onChanged();
        } else {
          productDetailsListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public Builder addProductDetailsList(
          com.zkart.model.OrderProto.ProductDetails.Builder builderForValue) {
        if (productDetailsListBuilder_ == null) {
          ensureProductDetailsListIsMutable();
          productDetailsList_.add(builderForValue.build());
          onChanged();
        } else {
          productDetailsListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public Builder addProductDetailsList(
          int index, com.zkart.model.OrderProto.ProductDetails.Builder builderForValue) {
        if (productDetailsListBuilder_ == null) {
          ensureProductDetailsListIsMutable();
          productDetailsList_.add(index, builderForValue.build());
          onChanged();
        } else {
          productDetailsListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public Builder addAllProductDetailsList(
          java.lang.Iterable<? extends com.zkart.model.OrderProto.ProductDetails> values) {
        if (productDetailsListBuilder_ == null) {
          ensureProductDetailsListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, productDetailsList_);
          onChanged();
        } else {
          productDetailsListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public Builder clearProductDetailsList() {
        if (productDetailsListBuilder_ == null) {
          productDetailsList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          productDetailsListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public Builder removeProductDetailsList(int index) {
        if (productDetailsListBuilder_ == null) {
          ensureProductDetailsListIsMutable();
          productDetailsList_.remove(index);
          onChanged();
        } else {
          productDetailsListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public com.zkart.model.OrderProto.ProductDetails.Builder getProductDetailsListBuilder(
          int index) {
        return getProductDetailsListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public com.zkart.model.OrderProto.ProductDetailsOrBuilder getProductDetailsListOrBuilder(
          int index) {
        if (productDetailsListBuilder_ == null) {
          return productDetailsList_.get(index);  } else {
          return productDetailsListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public java.util.List<? extends com.zkart.model.OrderProto.ProductDetailsOrBuilder> 
           getProductDetailsListOrBuilderList() {
        if (productDetailsListBuilder_ != null) {
          return productDetailsListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(productDetailsList_);
        }
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public com.zkart.model.OrderProto.ProductDetails.Builder addProductDetailsListBuilder() {
        return getProductDetailsListFieldBuilder().addBuilder(
            com.zkart.model.OrderProto.ProductDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public com.zkart.model.OrderProto.ProductDetails.Builder addProductDetailsListBuilder(
          int index) {
        return getProductDetailsListFieldBuilder().addBuilder(
            index, com.zkart.model.OrderProto.ProductDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .ProductDetails productDetailsList = 9;</code>
       */
      public java.util.List<com.zkart.model.OrderProto.ProductDetails.Builder> 
           getProductDetailsListBuilderList() {
        return getProductDetailsListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.OrderProto.ProductDetails, com.zkart.model.OrderProto.ProductDetails.Builder, com.zkart.model.OrderProto.ProductDetailsOrBuilder> 
          getProductDetailsListFieldBuilder() {
        if (productDetailsListBuilder_ == null) {
          productDetailsListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zkart.model.OrderProto.ProductDetails, com.zkart.model.OrderProto.ProductDetails.Builder, com.zkart.model.OrderProto.ProductDetailsOrBuilder>(
                  productDetailsList_,
                  ((bitField0_ & 0x00000100) != 0),
                  getParentForChildren(),
                  isClean());
          productDetailsList_ = null;
        }
        return productDetailsListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Order)
    }

    // @@protoc_insertion_point(class_scope:Order)
    private static final com.zkart.model.OrderProto.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.OrderProto.Order();
    }

    public static com.zkart.model.OrderProto.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      @java.lang.Override
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.OrderProto.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 productId = 1;</code>
     * @return The productId.
     */
    int getProductId();

    /**
     * <code>int32 count = 2;</code>
     * @return The count.
     */
    int getCount();

    /**
     * <code>bool isInDeal = 3;</code>
     * @return The isInDeal.
     */
    boolean getIsInDeal();

    /**
     * <code>int32 dealPercent = 5;</code>
     * @return The dealPercent.
     */
    int getDealPercent();
  }
  /**
   * Protobuf type {@code ProductDetails}
   */
  public static final class ProductDetails extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProductDetails)
      ProductDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ProductDetails.class.getName());
    }
    // Use ProductDetails.newBuilder() to construct.
    private ProductDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProductDetails() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.OrderProto.internal_static_ProductDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.OrderProto.internal_static_ProductDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.OrderProto.ProductDetails.class, com.zkart.model.OrderProto.ProductDetails.Builder.class);
    }

    public static final int PRODUCTID_FIELD_NUMBER = 1;
    private int productId_ = 0;
    /**
     * <code>int32 productId = 1;</code>
     * @return The productId.
     */
    @java.lang.Override
    public int getProductId() {
      return productId_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_ = 0;
    /**
     * <code>int32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    public static final int ISINDEAL_FIELD_NUMBER = 3;
    private boolean isInDeal_ = false;
    /**
     * <code>bool isInDeal = 3;</code>
     * @return The isInDeal.
     */
    @java.lang.Override
    public boolean getIsInDeal() {
      return isInDeal_;
    }

    public static final int DEALPERCENT_FIELD_NUMBER = 5;
    private int dealPercent_ = 0;
    /**
     * <code>int32 dealPercent = 5;</code>
     * @return The dealPercent.
     */
    @java.lang.Override
    public int getDealPercent() {
      return dealPercent_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (productId_ != 0) {
        output.writeInt32(1, productId_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      if (isInDeal_ != false) {
        output.writeBool(3, isInDeal_);
      }
      if (dealPercent_ != 0) {
        output.writeInt32(5, dealPercent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (productId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, productId_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (isInDeal_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isInDeal_);
      }
      if (dealPercent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, dealPercent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.OrderProto.ProductDetails)) {
        return super.equals(obj);
      }
      com.zkart.model.OrderProto.ProductDetails other = (com.zkart.model.OrderProto.ProductDetails) obj;

      if (getProductId()
          != other.getProductId()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (getIsInDeal()
          != other.getIsInDeal()) return false;
      if (getDealPercent()
          != other.getDealPercent()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + ISINDEAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsInDeal());
      hash = (37 * hash) + DEALPERCENT_FIELD_NUMBER;
      hash = (53 * hash) + getDealPercent();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.OrderProto.ProductDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.ProductDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.ProductDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.ProductDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.ProductDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.ProductDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.ProductDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.ProductDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.OrderProto.ProductDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.OrderProto.ProductDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.ProductDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.ProductDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.OrderProto.ProductDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductDetails)
        com.zkart.model.OrderProto.ProductDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.OrderProto.internal_static_ProductDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.OrderProto.internal_static_ProductDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.OrderProto.ProductDetails.class, com.zkart.model.OrderProto.ProductDetails.Builder.class);
      }

      // Construct using com.zkart.model.OrderProto.ProductDetails.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        productId_ = 0;
        count_ = 0;
        isInDeal_ = false;
        dealPercent_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.OrderProto.internal_static_ProductDetails_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.ProductDetails getDefaultInstanceForType() {
        return com.zkart.model.OrderProto.ProductDetails.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.ProductDetails build() {
        com.zkart.model.OrderProto.ProductDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.ProductDetails buildPartial() {
        com.zkart.model.OrderProto.ProductDetails result = new com.zkart.model.OrderProto.ProductDetails(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.zkart.model.OrderProto.ProductDetails result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.productId_ = productId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.count_ = count_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isInDeal_ = isInDeal_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.dealPercent_ = dealPercent_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.OrderProto.ProductDetails) {
          return mergeFrom((com.zkart.model.OrderProto.ProductDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.OrderProto.ProductDetails other) {
        if (other == com.zkart.model.OrderProto.ProductDetails.getDefaultInstance()) return this;
        if (other.getProductId() != 0) {
          setProductId(other.getProductId());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getIsInDeal() != false) {
          setIsInDeal(other.getIsInDeal());
        }
        if (other.getDealPercent() != 0) {
          setDealPercent(other.getDealPercent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                productId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                count_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                isInDeal_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 40: {
                dealPercent_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int productId_ ;
      /**
       * <code>int32 productId = 1;</code>
       * @return The productId.
       */
      @java.lang.Override
      public int getProductId() {
        return productId_;
      }
      /**
       * <code>int32 productId = 1;</code>
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(int value) {

        productId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 productId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        productId_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 2;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {

        count_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      private boolean isInDeal_ ;
      /**
       * <code>bool isInDeal = 3;</code>
       * @return The isInDeal.
       */
      @java.lang.Override
      public boolean getIsInDeal() {
        return isInDeal_;
      }
      /**
       * <code>bool isInDeal = 3;</code>
       * @param value The isInDeal to set.
       * @return This builder for chaining.
       */
      public Builder setIsInDeal(boolean value) {

        isInDeal_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool isInDeal = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsInDeal() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isInDeal_ = false;
        onChanged();
        return this;
      }

      private int dealPercent_ ;
      /**
       * <code>int32 dealPercent = 5;</code>
       * @return The dealPercent.
       */
      @java.lang.Override
      public int getDealPercent() {
        return dealPercent_;
      }
      /**
       * <code>int32 dealPercent = 5;</code>
       * @param value The dealPercent to set.
       * @return This builder for chaining.
       */
      public Builder setDealPercent(int value) {

        dealPercent_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dealPercent = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDealPercent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dealPercent_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProductDetails)
    }

    // @@protoc_insertion_point(class_scope:ProductDetails)
    private static final com.zkart.model.OrderProto.ProductDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.OrderProto.ProductDetails();
    }

    public static com.zkart.model.OrderProto.ProductDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductDetails>
        PARSER = new com.google.protobuf.AbstractParser<ProductDetails>() {
      @java.lang.Override
      public ProductDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProductDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.OrderProto.ProductDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrdersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Orders)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Order orders = 1;</code>
     */
    java.util.List<com.zkart.model.OrderProto.Order> 
        getOrdersList();
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    com.zkart.model.OrderProto.Order getOrders(int index);
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    int getOrdersCount();
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    java.util.List<? extends com.zkart.model.OrderProto.OrderOrBuilder> 
        getOrdersOrBuilderList();
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    com.zkart.model.OrderProto.OrderOrBuilder getOrdersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Orders}
   */
  public static final class Orders extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Orders)
      OrdersOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Orders.class.getName());
    }
    // Use Orders.newBuilder() to construct.
    private Orders(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Orders() {
      orders_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.OrderProto.internal_static_Orders_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.OrderProto.internal_static_Orders_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.OrderProto.Orders.class, com.zkart.model.OrderProto.Orders.Builder.class);
    }

    public static final int ORDERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.zkart.model.OrderProto.Order> orders_;
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.zkart.model.OrderProto.Order> getOrdersList() {
      return orders_;
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.zkart.model.OrderProto.OrderOrBuilder> 
        getOrdersOrBuilderList() {
      return orders_;
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public int getOrdersCount() {
      return orders_.size();
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.OrderProto.Order getOrders(int index) {
      return orders_.get(index);
    }
    /**
     * <code>repeated .Order orders = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.OrderProto.OrderOrBuilder getOrdersOrBuilder(
        int index) {
      return orders_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < orders_.size(); i++) {
        output.writeMessage(1, orders_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < orders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, orders_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.OrderProto.Orders)) {
        return super.equals(obj);
      }
      com.zkart.model.OrderProto.Orders other = (com.zkart.model.OrderProto.Orders) obj;

      if (!getOrdersList()
          .equals(other.getOrdersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOrdersCount() > 0) {
        hash = (37 * hash) + ORDERS_FIELD_NUMBER;
        hash = (53 * hash) + getOrdersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.OrderProto.Orders parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.OrderProto.Orders parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.OrderProto.Orders parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.OrderProto.Orders parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.OrderProto.Orders prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Orders}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Orders)
        com.zkart.model.OrderProto.OrdersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.OrderProto.internal_static_Orders_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.OrderProto.internal_static_Orders_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.OrderProto.Orders.class, com.zkart.model.OrderProto.Orders.Builder.class);
      }

      // Construct using com.zkart.model.OrderProto.Orders.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
        } else {
          orders_ = null;
          ordersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.OrderProto.internal_static_Orders_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Orders getDefaultInstanceForType() {
        return com.zkart.model.OrderProto.Orders.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Orders build() {
        com.zkart.model.OrderProto.Orders result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.OrderProto.Orders buildPartial() {
        com.zkart.model.OrderProto.Orders result = new com.zkart.model.OrderProto.Orders(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.zkart.model.OrderProto.Orders result) {
        if (ordersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            orders_ = java.util.Collections.unmodifiableList(orders_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.orders_ = orders_;
        } else {
          result.orders_ = ordersBuilder_.build();
        }
      }

      private void buildPartial0(com.zkart.model.OrderProto.Orders result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.OrderProto.Orders) {
          return mergeFrom((com.zkart.model.OrderProto.Orders)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.OrderProto.Orders other) {
        if (other == com.zkart.model.OrderProto.Orders.getDefaultInstance()) return this;
        if (ordersBuilder_ == null) {
          if (!other.orders_.isEmpty()) {
            if (orders_.isEmpty()) {
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrdersIsMutable();
              orders_.addAll(other.orders_);
            }
            onChanged();
          }
        } else {
          if (!other.orders_.isEmpty()) {
            if (ordersBuilder_.isEmpty()) {
              ordersBuilder_.dispose();
              ordersBuilder_ = null;
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ordersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOrdersFieldBuilder() : null;
            } else {
              ordersBuilder_.addAllMessages(other.orders_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.zkart.model.OrderProto.Order m =
                    input.readMessage(
                        com.zkart.model.OrderProto.Order.parser(),
                        extensionRegistry);
                if (ordersBuilder_ == null) {
                  ensureOrdersIsMutable();
                  orders_.add(m);
                } else {
                  ordersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zkart.model.OrderProto.Order> orders_ =
        java.util.Collections.emptyList();
      private void ensureOrdersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          orders_ = new java.util.ArrayList<com.zkart.model.OrderProto.Order>(orders_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.OrderProto.Order, com.zkart.model.OrderProto.Order.Builder, com.zkart.model.OrderProto.OrderOrBuilder> ordersBuilder_;

      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public java.util.List<com.zkart.model.OrderProto.Order> getOrdersList() {
        if (ordersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orders_);
        } else {
          return ordersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public int getOrdersCount() {
        if (ordersBuilder_ == null) {
          return orders_.size();
        } else {
          return ordersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.Order getOrders(int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);
        } else {
          return ordersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder setOrders(
          int index, com.zkart.model.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.set(index, value);
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder setOrders(
          int index, com.zkart.model.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.set(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(com.zkart.model.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(
          int index, com.zkart.model.OrderProto.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(index, value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(
          com.zkart.model.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addOrders(
          int index, com.zkart.model.OrderProto.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder addAllOrders(
          java.lang.Iterable<? extends com.zkart.model.OrderProto.Order> values) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orders_);
          onChanged();
        } else {
          ordersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder clearOrders() {
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ordersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public Builder removeOrders(int index) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.remove(index);
          onChanged();
        } else {
          ordersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.Order.Builder getOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.OrderOrBuilder getOrdersOrBuilder(
          int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);  } else {
          return ordersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public java.util.List<? extends com.zkart.model.OrderProto.OrderOrBuilder> 
           getOrdersOrBuilderList() {
        if (ordersBuilder_ != null) {
          return ordersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orders_);
        }
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.Order.Builder addOrdersBuilder() {
        return getOrdersFieldBuilder().addBuilder(
            com.zkart.model.OrderProto.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public com.zkart.model.OrderProto.Order.Builder addOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().addBuilder(
            index, com.zkart.model.OrderProto.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .Order orders = 1;</code>
       */
      public java.util.List<com.zkart.model.OrderProto.Order.Builder> 
           getOrdersBuilderList() {
        return getOrdersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.OrderProto.Order, com.zkart.model.OrderProto.Order.Builder, com.zkart.model.OrderProto.OrderOrBuilder> 
          getOrdersFieldBuilder() {
        if (ordersBuilder_ == null) {
          ordersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zkart.model.OrderProto.Order, com.zkart.model.OrderProto.Order.Builder, com.zkart.model.OrderProto.OrderOrBuilder>(
                  orders_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          orders_ = null;
        }
        return ordersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Orders)
    }

    // @@protoc_insertion_point(class_scope:Orders)
    private static final com.zkart.model.OrderProto.Orders DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.OrderProto.Orders();
    }

    public static com.zkart.model.OrderProto.Orders getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Orders>
        PARSER = new com.google.protobuf.AbstractParser<Orders>() {
      @java.lang.Override
      public Orders parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Orders> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Orders> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.OrderProto.Orders getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductDetails_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Orders_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Orders_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#com/zkart/dbFiles/proto/order.proto\"\322\001" +
      "\n\005Order\022\n\n\002id\030\001 \001(\005\022\016\n\006userId\030\002 \001(\005\022\022\n\nt" +
      "otalPrice\030\003 \001(\005\022\027\n\017isCouponApplied\030\004 \001(\010" +
      "\022\022\n\ncouponCode\030\005 \001(\t\022\027\n\017discountPercent\030" +
      "\006 \001(\005\022\022\n\nfinalPrice\030\007 \001(\005\022\022\n\ntimeStamps\030" +
      "\010 \001(\t\022+\n\022productDetailsList\030\t \003(\0132\017.Prod" +
      "uctDetails\"Y\n\016ProductDetails\022\021\n\tproductI" +
      "d\030\001 \001(\005\022\r\n\005count\030\002 \001(\005\022\020\n\010isInDeal\030\003 \001(\010" +
      "\022\023\n\013dealPercent\030\005 \001(\005\" \n\006Orders\022\026\n\006order" +
      "s\030\001 \003(\0132\006.OrderB\035\n\017com.zkart.modelB\nOrde" +
      "rProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "Id", "UserId", "TotalPrice", "IsCouponApplied", "CouponCode", "DiscountPercent", "FinalPrice", "TimeStamps", "ProductDetailsList", });
    internal_static_ProductDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProductDetails_descriptor,
        new java.lang.String[] { "ProductId", "Count", "IsInDeal", "DealPercent", });
    internal_static_Orders_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Orders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Orders_descriptor,
        new java.lang.String[] { "Orders", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
