// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/zkart/dbFiles/proto/user.proto
// Protobuf Java Version: 4.29.3

package com.zkart.model;

public final class UserProto {
  private UserProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      UserProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.BaseUser userDetails = 1;</code>
     * @return Whether the userDetails field is set.
     */
    boolean hasUserDetails();
    /**
     * <code>.BaseUser userDetails = 1;</code>
     * @return The userDetails.
     */
    com.zkart.model.BaseUserProto.BaseUser getUserDetails();
    /**
     * <code>.BaseUser userDetails = 1;</code>
     */
    com.zkart.model.BaseUserProto.BaseUserOrBuilder getUserDetailsOrBuilder();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        User.class.getName());
    }
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private User() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.UserProto.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.UserProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.UserProto.User.class, com.zkart.model.UserProto.User.Builder.class);
    }

    private int bitField0_;
    public static final int USERDETAILS_FIELD_NUMBER = 1;
    private com.zkart.model.BaseUserProto.BaseUser userDetails_;
    /**
     * <code>.BaseUser userDetails = 1;</code>
     * @return Whether the userDetails field is set.
     */
    @java.lang.Override
    public boolean hasUserDetails() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.BaseUser userDetails = 1;</code>
     * @return The userDetails.
     */
    @java.lang.Override
    public com.zkart.model.BaseUserProto.BaseUser getUserDetails() {
      return userDetails_ == null ? com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance() : userDetails_;
    }
    /**
     * <code>.BaseUser userDetails = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.BaseUserProto.BaseUserOrBuilder getUserDetailsOrBuilder() {
      return userDetails_ == null ? com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance() : userDetails_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getUserDetails());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUserDetails());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.UserProto.User)) {
        return super.equals(obj);
      }
      com.zkart.model.UserProto.User other = (com.zkart.model.UserProto.User) obj;

      if (hasUserDetails() != other.hasUserDetails()) return false;
      if (hasUserDetails()) {
        if (!getUserDetails()
            .equals(other.getUserDetails())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserDetails()) {
        hash = (37 * hash) + USERDETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getUserDetails().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.UserProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.UserProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.zkart.model.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.UserProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.UserProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.UserProto.User.class, com.zkart.model.UserProto.User.Builder.class);
      }

      // Construct using com.zkart.model.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getUserDetailsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userDetails_ = null;
        if (userDetailsBuilder_ != null) {
          userDetailsBuilder_.dispose();
          userDetailsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.UserProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.UserProto.User getDefaultInstanceForType() {
        return com.zkart.model.UserProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.UserProto.User build() {
        com.zkart.model.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.UserProto.User buildPartial() {
        com.zkart.model.UserProto.User result = new com.zkart.model.UserProto.User(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.zkart.model.UserProto.User result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userDetails_ = userDetailsBuilder_ == null
              ? userDetails_
              : userDetailsBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.UserProto.User) {
          return mergeFrom((com.zkart.model.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.UserProto.User other) {
        if (other == com.zkart.model.UserProto.User.getDefaultInstance()) return this;
        if (other.hasUserDetails()) {
          mergeUserDetails(other.getUserDetails());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getUserDetailsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.zkart.model.BaseUserProto.BaseUser userDetails_;
      private com.google.protobuf.SingleFieldBuilder<
          com.zkart.model.BaseUserProto.BaseUser, com.zkart.model.BaseUserProto.BaseUser.Builder, com.zkart.model.BaseUserProto.BaseUserOrBuilder> userDetailsBuilder_;
      /**
       * <code>.BaseUser userDetails = 1;</code>
       * @return Whether the userDetails field is set.
       */
      public boolean hasUserDetails() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.BaseUser userDetails = 1;</code>
       * @return The userDetails.
       */
      public com.zkart.model.BaseUserProto.BaseUser getUserDetails() {
        if (userDetailsBuilder_ == null) {
          return userDetails_ == null ? com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance() : userDetails_;
        } else {
          return userDetailsBuilder_.getMessage();
        }
      }
      /**
       * <code>.BaseUser userDetails = 1;</code>
       */
      public Builder setUserDetails(com.zkart.model.BaseUserProto.BaseUser value) {
        if (userDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userDetails_ = value;
        } else {
          userDetailsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.BaseUser userDetails = 1;</code>
       */
      public Builder setUserDetails(
          com.zkart.model.BaseUserProto.BaseUser.Builder builderForValue) {
        if (userDetailsBuilder_ == null) {
          userDetails_ = builderForValue.build();
        } else {
          userDetailsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.BaseUser userDetails = 1;</code>
       */
      public Builder mergeUserDetails(com.zkart.model.BaseUserProto.BaseUser value) {
        if (userDetailsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            userDetails_ != null &&
            userDetails_ != com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance()) {
            getUserDetailsBuilder().mergeFrom(value);
          } else {
            userDetails_ = value;
          }
        } else {
          userDetailsBuilder_.mergeFrom(value);
        }
        if (userDetails_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.BaseUser userDetails = 1;</code>
       */
      public Builder clearUserDetails() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userDetails_ = null;
        if (userDetailsBuilder_ != null) {
          userDetailsBuilder_.dispose();
          userDetailsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.BaseUser userDetails = 1;</code>
       */
      public com.zkart.model.BaseUserProto.BaseUser.Builder getUserDetailsBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserDetailsFieldBuilder().getBuilder();
      }
      /**
       * <code>.BaseUser userDetails = 1;</code>
       */
      public com.zkart.model.BaseUserProto.BaseUserOrBuilder getUserDetailsOrBuilder() {
        if (userDetailsBuilder_ != null) {
          return userDetailsBuilder_.getMessageOrBuilder();
        } else {
          return userDetails_ == null ?
              com.zkart.model.BaseUserProto.BaseUser.getDefaultInstance() : userDetails_;
        }
      }
      /**
       * <code>.BaseUser userDetails = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.zkart.model.BaseUserProto.BaseUser, com.zkart.model.BaseUserProto.BaseUser.Builder, com.zkart.model.BaseUserProto.BaseUserOrBuilder> 
          getUserDetailsFieldBuilder() {
        if (userDetailsBuilder_ == null) {
          userDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.zkart.model.BaseUserProto.BaseUser, com.zkart.model.BaseUserProto.BaseUser.Builder, com.zkart.model.BaseUserProto.BaseUserOrBuilder>(
                  getUserDetails(),
                  getParentForChildren(),
                  isClean());
          userDetails_ = null;
        }
        return userDetailsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.zkart.model.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.UserProto.User();
    }

    public static com.zkart.model.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UsersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Users)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .User users = 1;</code>
     */
    java.util.List<com.zkart.model.UserProto.User> 
        getUsersList();
    /**
     * <code>repeated .User users = 1;</code>
     */
    com.zkart.model.UserProto.User getUsers(int index);
    /**
     * <code>repeated .User users = 1;</code>
     */
    int getUsersCount();
    /**
     * <code>repeated .User users = 1;</code>
     */
    java.util.List<? extends com.zkart.model.UserProto.UserOrBuilder> 
        getUsersOrBuilderList();
    /**
     * <code>repeated .User users = 1;</code>
     */
    com.zkart.model.UserProto.UserOrBuilder getUsersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Users}
   */
  public static final class Users extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Users)
      UsersOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Users.class.getName());
    }
    // Use Users.newBuilder() to construct.
    private Users(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Users() {
      users_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zkart.model.UserProto.internal_static_Users_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zkart.model.UserProto.internal_static_Users_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zkart.model.UserProto.Users.class, com.zkart.model.UserProto.Users.Builder.class);
    }

    public static final int USERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.zkart.model.UserProto.User> users_;
    /**
     * <code>repeated .User users = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.zkart.model.UserProto.User> getUsersList() {
      return users_;
    }
    /**
     * <code>repeated .User users = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.zkart.model.UserProto.UserOrBuilder> 
        getUsersOrBuilderList() {
      return users_;
    }
    /**
     * <code>repeated .User users = 1;</code>
     */
    @java.lang.Override
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <code>repeated .User users = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.UserProto.User getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <code>repeated .User users = 1;</code>
     */
    @java.lang.Override
    public com.zkart.model.UserProto.UserOrBuilder getUsersOrBuilder(
        int index) {
      return users_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < users_.size(); i++) {
        output.writeMessage(1, users_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < users_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, users_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zkart.model.UserProto.Users)) {
        return super.equals(obj);
      }
      com.zkart.model.UserProto.Users other = (com.zkart.model.UserProto.Users) obj;

      if (!getUsersList()
          .equals(other.getUsersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUsersCount() > 0) {
        hash = (37 * hash) + USERS_FIELD_NUMBER;
        hash = (53 * hash) + getUsersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zkart.model.UserProto.Users parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.UserProto.Users parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.UserProto.Users parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.UserProto.Users parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.UserProto.Users parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zkart.model.UserProto.Users parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zkart.model.UserProto.Users parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.UserProto.Users parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.zkart.model.UserProto.Users parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.zkart.model.UserProto.Users parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zkart.model.UserProto.Users parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.zkart.model.UserProto.Users parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zkart.model.UserProto.Users prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Users}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Users)
        com.zkart.model.UserProto.UsersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zkart.model.UserProto.internal_static_Users_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zkart.model.UserProto.internal_static_Users_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zkart.model.UserProto.Users.class, com.zkart.model.UserProto.Users.Builder.class);
      }

      // Construct using com.zkart.model.UserProto.Users.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
        } else {
          users_ = null;
          usersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zkart.model.UserProto.internal_static_Users_descriptor;
      }

      @java.lang.Override
      public com.zkart.model.UserProto.Users getDefaultInstanceForType() {
        return com.zkart.model.UserProto.Users.getDefaultInstance();
      }

      @java.lang.Override
      public com.zkart.model.UserProto.Users build() {
        com.zkart.model.UserProto.Users result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zkart.model.UserProto.Users buildPartial() {
        com.zkart.model.UserProto.Users result = new com.zkart.model.UserProto.Users(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.zkart.model.UserProto.Users result) {
        if (usersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            users_ = java.util.Collections.unmodifiableList(users_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.users_ = users_;
        } else {
          result.users_ = usersBuilder_.build();
        }
      }

      private void buildPartial0(com.zkart.model.UserProto.Users result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zkart.model.UserProto.Users) {
          return mergeFrom((com.zkart.model.UserProto.Users)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zkart.model.UserProto.Users other) {
        if (other == com.zkart.model.UserProto.Users.getDefaultInstance()) return this;
        if (usersBuilder_ == null) {
          if (!other.users_.isEmpty()) {
            if (users_.isEmpty()) {
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUsersIsMutable();
              users_.addAll(other.users_);
            }
            onChanged();
          }
        } else {
          if (!other.users_.isEmpty()) {
            if (usersBuilder_.isEmpty()) {
              usersBuilder_.dispose();
              usersBuilder_ = null;
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
              usersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUsersFieldBuilder() : null;
            } else {
              usersBuilder_.addAllMessages(other.users_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.zkart.model.UserProto.User m =
                    input.readMessage(
                        com.zkart.model.UserProto.User.parser(),
                        extensionRegistry);
                if (usersBuilder_ == null) {
                  ensureUsersIsMutable();
                  users_.add(m);
                } else {
                  usersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zkart.model.UserProto.User> users_ =
        java.util.Collections.emptyList();
      private void ensureUsersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          users_ = new java.util.ArrayList<com.zkart.model.UserProto.User>(users_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.UserProto.User, com.zkart.model.UserProto.User.Builder, com.zkart.model.UserProto.UserOrBuilder> usersBuilder_;

      /**
       * <code>repeated .User users = 1;</code>
       */
      public java.util.List<com.zkart.model.UserProto.User> getUsersList() {
        if (usersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(users_);
        } else {
          return usersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public int getUsersCount() {
        if (usersBuilder_ == null) {
          return users_.size();
        } else {
          return usersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public com.zkart.model.UserProto.User getUsers(int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);
        } else {
          return usersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder setUsers(
          int index, com.zkart.model.UserProto.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.set(index, value);
          onChanged();
        } else {
          usersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder setUsers(
          int index, com.zkart.model.UserProto.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.set(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addUsers(com.zkart.model.UserProto.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(value);
          onChanged();
        } else {
          usersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addUsers(
          int index, com.zkart.model.UserProto.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(index, value);
          onChanged();
        } else {
          usersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addUsers(
          com.zkart.model.UserProto.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addUsers(
          int index, com.zkart.model.UserProto.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addAllUsers(
          java.lang.Iterable<? extends com.zkart.model.UserProto.User> values) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, users_);
          onChanged();
        } else {
          usersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder clearUsers() {
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          usersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder removeUsers(int index) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.remove(index);
          onChanged();
        } else {
          usersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public com.zkart.model.UserProto.User.Builder getUsersBuilder(
          int index) {
        return getUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public com.zkart.model.UserProto.UserOrBuilder getUsersOrBuilder(
          int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);  } else {
          return usersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public java.util.List<? extends com.zkart.model.UserProto.UserOrBuilder> 
           getUsersOrBuilderList() {
        if (usersBuilder_ != null) {
          return usersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(users_);
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public com.zkart.model.UserProto.User.Builder addUsersBuilder() {
        return getUsersFieldBuilder().addBuilder(
            com.zkart.model.UserProto.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public com.zkart.model.UserProto.User.Builder addUsersBuilder(
          int index) {
        return getUsersFieldBuilder().addBuilder(
            index, com.zkart.model.UserProto.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public java.util.List<com.zkart.model.UserProto.User.Builder> 
           getUsersBuilderList() {
        return getUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zkart.model.UserProto.User, com.zkart.model.UserProto.User.Builder, com.zkart.model.UserProto.UserOrBuilder> 
          getUsersFieldBuilder() {
        if (usersBuilder_ == null) {
          usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zkart.model.UserProto.User, com.zkart.model.UserProto.User.Builder, com.zkart.model.UserProto.UserOrBuilder>(
                  users_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          users_ = null;
        }
        return usersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Users)
    }

    // @@protoc_insertion_point(class_scope:Users)
    private static final com.zkart.model.UserProto.Users DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zkart.model.UserProto.Users();
    }

    public static com.zkart.model.UserProto.Users getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Users>
        PARSER = new com.google.protobuf.AbstractParser<Users>() {
      @java.lang.Override
      public Users parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Users> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Users> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zkart.model.UserProto.Users getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Users_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Users_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"com/zkart/dbFiles/proto/user.proto\032&co" +
      "m/zkart/dbFiles/proto/baseUser.proto\"&\n\004" +
      "User\022\036\n\013userDetails\030\001 \001(\0132\t.BaseUser\"\035\n\005" +
      "Users\022\024\n\005users\030\001 \003(\0132\005.UserB\034\n\017com.zkart" +
      ".modelB\tUserProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zkart.model.BaseUserProto.getDescriptor(),
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "UserDetails", });
    internal_static_Users_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Users_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Users_descriptor,
        new java.lang.String[] { "Users", });
    descriptor.resolveAllFeaturesImmutable();
    com.zkart.model.BaseUserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
